title: Bilel Mezhoud 
logo: /Portfolio/assets/img/profile_pic.png

description: "Junior Data Scientist and Machine Learning Professional with expertise in Python, Java, SQL, and GIS systems development using ArcGIS."
theme: jekyll-theme-Cayman

social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/bilel-mezhoud/
  - name: GitHub
    url: https://github.com/BilelMezhoud

# SEO and metadata settings
seo:
  title: "Bilel Mezhoud - Data Scientist & Machine Learning Professional"
  description: "Explore my portfolio showcasing projects in AI, GIS, and software development."
  twitter_card: summary_large_image
